# Argumentene til range() var satt i feil rekkefÃ¸lge
for tall in range(5, 20, 3):
    print(tall)